//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prilozhenie.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public System.DateTime DateofContract { get; set; }
        public string RieltorsFullName { get; set; }
        public string UsersFullName { get; set; }
        public string Period { get; set; }
        public int TypeOfRoomID { get; set; }
        public string Amount { get; set; }
    
        public virtual TypeOfRooms TypeOfRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
