//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prilozhenie.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int ID { get; set; }
        public string address { get; set; }
        public string Town { get; set; }
        public string Price { get; set; }
        public int CountOfRoomID { get; set; }
        public int TypeOfRoomID { get; set; }
    
        public virtual CountsOfRooms CountsOfRooms { get; set; }
        public virtual TypeOfRooms TypeOfRooms { get; set; }
    }
}
