//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prilozhenie.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int RequestsID { get; set; }
        public int ContractID { get; set; }
        public int RoomID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
